#!/usr/bin/env bash
#Script that displays I am invincible!!! when receiving a SIGTERM signal
NAME="To infinity and beyond"
trap "echo 'I am invincible!!!'" SIGTERM
while true; do
    echo "$NAME"
    sleep 2
done